# Generated by Django 4.1 on 2023-03-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.IntegerField(verbose_name='centro de custo')),
                ('codigo_integracao', models.CharField(choices=[(0, 'erp'), (1, 'crm'), (2, 'bi'), (3, 'api'), (4, 'e-commerce'), (5, 'loT')], max_length=1, verbose_name='Integrações')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='Cnpj')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('pais', models.CharField(max_length=255, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='nome completo')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('telefone', models.CharField(max_length=255, verbose_name='telefone')),
                ('data_nascimento', models.DateField(max_length=255, verbose_name='Data de nascimento')),
                ('data_ingresso', models.DateField(max_length=255, verbose_name='Data de ingresso')),
                ('data_desligamento', models.DateField(max_length=255, verbose_name='Data de desligamento')),
                ('ativo', models.BooleanField(default=True, max_length=255, verbose_name='Ativo')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('departamento_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='departamento_sede')),
            ],
        ),
    ]
