# Generated by Django 4.1 on 2023-03-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo_integracao',
            field=models.IntegerField(choices=[(0, 'erp'), (1, 'crm'), (2, 'bi'), (3, 'api'), (4, 'e-commerce'), (5, 'loT')], verbose_name='Integrações'),
        ),
    ]
