# Generated by Django 4.1 on 2023-03-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_departamento_codigo_integracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de desligamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_ingresso',
            field=models.DateField(auto_created=True, verbose_name='Data de ingresso'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='telefone'),
        ),
    ]
